### ISSUE TITLE
Repo link displayed on npmjs is incorrect.

### ISSUE THREAD

**Issue by jmelvin-r7** [planttheidea/react-parm#5]
The following lines in package.json should be updated to the correct urls: 

- https://github.com/planttheidea/react-parm/blob/master/package.json#L27
- https://github.com/planttheidea/react-parm/blob/master/package.json#L68
- https://github.com/planttheidea/react-parm/blob/master/package.json#L78

**Comment by planttheidea** [comment]
Fixed with the release of `2.1.0`. Thanks!
